name: New pre release
run-name: Create new pre release.
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "wagoio/import.txt"
          prerelease: true
          makeLatest: false
          allowUpdates: true
          replacesArtifacts: true
